const GAME_WIDTH = 360;
const GAME_HEIGHT = 560;

const PLAYER_Y = GAME_HEIGHT - 46;
const PLAYER_WIDTH = 74;
const PLAYER_HEIGHT = 34;
const PLAYER_SPEED = 320;
const PLAYER_LIVES = 3;

const BEER_SIZE = 30;
const BEER_SPEED_MIN = 110;
const BEER_SPEED_MAX = 170;
const BEER_SPAWN_MIN_MS = 500;
const BEER_SPAWN_MAX_MS = 900;
const BEER_SCORE = 50;

const GOLDEN_BEER_CHANCE = 0.18;
const GOLDEN_BEER_SCORE = 150;

const BAD_SIZE = 28;
const BAD_SPEED_MIN = 140;
const BAD_SPEED_MAX = 220;
const BAD_SPAWN_MIN_MS = 700;
const BAD_SPAWN_MAX_MS = 1300;

const DIFFICULTY_SCORE_STEP = 500;
const DIFFICULTY_SPEED_BONUS = 22;
const DIFFICULTY_SPAWN_BONUS_MS = 60;
const DIFFICULTY_MAX_STEPS = 6;

const BEST_SCORE_KEY = "beerCatchBestScore";
