const GAME_WIDTH = 360;
const GAME_HEIGHT = 560;

const PLAYER_X = 46;
const PLAYER_SIZE = 30;
const PLAYER_SPEED = 230;
const PLAYER_LIVES = 3;

const ARROW_WIDTH = 22;
const ARROW_HEIGHT = 5;
const ARROW_SPEED = 400;
const ARROW_COOLDOWN_MS = 260;

const BALLOON_SIZE = 32;
const BALLOON_SPEED_MIN = 60;
const BALLOON_SPEED_MAX = 100;
const BALLOON_BOB_AMPLITUDE = 26;
const BALLOON_BOB_FREQ_MIN = 1.2;
const BALLOON_BOB_FREQ_MAX = 2.2;
const BALLOON_SPAWN_MIN_MS = 700;
const BALLOON_SPAWN_MAX_MS = 1300;
const BALLOON_SCORE = 100;

const ROCK_SIZE = 26;
const ROCK_SPEED_MIN = 130;
const ROCK_SPEED_MAX = 210;
const ROCK_SPAWN_MIN_MS = 900;
const ROCK_SPAWN_MAX_MS = 1700;
const ROCK_SCORE = 60;

const DIFFICULTY_SCORE_STEP = 800;
const DIFFICULTY_SPEED_BONUS = 18;
const DIFFICULTY_MAX_STEPS = 6;

const BEST_SCORE_KEY = "pooyanBestScore";
