const GAME_WIDTH = 360;
const GAME_HEIGHT = 560;

const ROAD_WIDTH = 220;
const ROAD_CURVE_AMPLITUDE = 50;
const ROAD_CURVE_FREQ = 0.0022;

const PLAYER_SCREEN_Y = GAME_HEIGHT * 0.78;
const PLAYER_WIDTH = 30;
const PLAYER_HEIGHT = 46;
const PLAYER_TURN_SPEED = 240;

const CRUISE_SPEED = 170;
const MIN_SPEED = 90;
const MAX_SPEED = 320;
const ACCEL_RATE = 220;
const BRAKE_RATE = 260;
const SPEED_DECAY_RATE = 90;

const FUEL_MAX = 100;
const FUEL_DRAIN_PER_SEC = 3.2;
const FUEL_PICKUP_AMOUNT = 28;

const TRAFFIC_WIDTH = 30;
const TRAFFIC_HEIGHT = 46;
const TRAFFIC_SPAWN_MIN_MS = 750;
const TRAFFIC_SPAWN_MAX_MS = 1350;
const TRAFFIC_SPEED_VARIANCE = 60;

const FUEL_ITEM_SIZE = 26;
const FUEL_SPAWN_MIN_MS = 4500;
const FUEL_SPAWN_MAX_MS = 7500;

const SPAWN_SCREEN_Y = -60;
const DESPAWN_SCREEN_Y = GAME_HEIGHT + 60;

const BEST_SCORE_KEY = "roadFighterBestScore";
