const GAME_WIDTH = 360;
const GAME_HEIGHT = 560;

const PLAYER_SIZE = 26;
const PLAYER_SPEED = 260;
const PLAYER_LIVES = 3;
const PLAYER_MAX_X_RATIO = 0.6;

const BULLET_WIDTH = 14;
const BULLET_HEIGHT = 4;
const BULLET_SPEED = 480;
const FIRE_COOLDOWN_BY_LEVEL = [280, 210, 150];
const WEAPON_MAX_LEVEL = 3;

const ENEMY_BULLET_SIZE = 6;
const ENEMY_BULLET_SPEED = 220;

const DRONE_SIZE = 22;
const DRONE_SPEED_MIN = 110;
const DRONE_SPEED_MAX = 170;
const DRONE_SCORE = 60;
const DRONE_HP = 1;

const CRUISER_SIZE = 32;
const CRUISER_SPEED_MIN = 70;
const CRUISER_SPEED_MAX = 110;
const CRUISER_SCORE = 140;
const CRUISER_HP = 2;
const CRUISER_FIRE_MIN_MS = 900;
const CRUISER_FIRE_MAX_MS = 1600;

const ASTEROID_SIZE = 28;
const ASTEROID_SPEED_MIN = 90;
const ASTEROID_SPEED_MAX = 150;
const ASTEROID_SCORE = 40;
const ASTEROID_HP = 1;

const ENEMY_SPAWN_MIN_MS = 550;
const ENEMY_SPAWN_MAX_MS = 1050;

const POWERUP_SIZE = 18;
const POWERUP_SPEED = 130;
const POWERUP_DROP_CHANCE = 0.16;

const DIFFICULTY_SCORE_STEP = 900;
const DIFFICULTY_SPEED_BONUS = 16;
const DIFFICULTY_MAX_STEPS = 7;

const BEST_SCORE_KEY = "spaceImpactBestScore";
